config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :races

  resources :types

	root 'home#index'
	resources :cartes
end

  

app/models/carte.rb
class Carte < ActiveRecord::Base
	belongs_to :type
	has_many :carte_races
	has_many :races, through: :carte_races
end

app/models/carte_race.rb
class CarteRace < ActiveRecord::Base
  belongs_to :carte
  belongs_to :race
end

app/models/race.rb
class Race < ActiveRecord::Base
  belongs_to :type
  has_many :carte_races
  has_many :cartes, through: :carte_races
end

app/models/type.rb
class Type < ActiveRecord::Base
	has_many :cartes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cartes_controller.rb
class CartesController < ApplicationController
	before_action :set_carte, only: [:show, :edit, :update, :destroy]
	
	def index
		@cartes = Carte.paginate(page: params[:page], per_page: 3).includes(:type).order(number: :asc)
	end


	def show
	end
	
	def new
		@carte = Carte.new
	end
	
	def create
		@carte = Carte.new carte_params
		if @carte.save
			flash[:sucess] = "La Carte #{@carte.name} a bien été ajoutée"
			redirect_to @carte
		else 
			render 'new'
		end
	end
	
	def edit
	end
	
	def update
		if @carte.update carte_params
			flash[:sucess] = "La Carte #{@carte.name} a bien été mise à jour"
			redirect_to @carte
		else
			render 'edit'
		end
	end
	
	def destroy
		@carte.destroy
		flash[:alert] = "La Carte #{@carte.name} a bien été supprimée"
		redirect_to cartes_path
	end
	
	private
	
	def set_carte
		@carte = Carte.includes(:races).find (params[:id])
	end
	
	def cartes_params 
		params.require(:carte).permit(:name, :number, :mana, :rarete, :type_id)
	end
	
	def carte_params
		params.require(:carte).permit(
			:name,
			:number,
			:mana,
			:rarete,
			:type_id,
			race_ids: []
		)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: [:show, :edit, :update, :destroy]

  # GET /races
  # GET /races.json
  def index
    @races = Race.all
  end

  # GET /races/1
  # GET /races/1.json
  def show
  end

  # GET /races/new
  def new
    @race = Race.new
  end

  # GET /races/1/edit
  def edit
  end

  # POST /races
  # POST /races.json
  def create
    @race = Race.new(race_params)

    respond_to do |format|
      if @race.save
        format.html { redirect_to @race, notice: 'Race was successfully created.' }
        format.json { render :show, status: :created, location: @race }
      else
        format.html { render :new }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /races/1
  # PATCH/PUT /races/1.json
  def update
    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to @race, notice: 'Race was successfully updated.' }
        format.json { render :show, status: :ok, location: @race }
      else
        format.html { render :edit }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1
  # DELETE /races/1.json
  def destroy
    @race.destroy
    respond_to do |format|
      format.html { redirect_to races_url, notice: 'Race was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
      @race = Race.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def race_params
      params.require(:race).permit(:name, :description, :type_id)
    end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:name, :color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/types_helper.rb
module TypesHelper 
	def type_badge(type, name = nil) 
		name ||= type.name
		raw link_to type_badge_link(name, type.color), type_path(type.id) 
	end 
	
	def type_badge_link(name, color) 
		raw "<span style='background-color:#{color}' class='badge'> 
		#{name} 
		</span>" 
	end 
end

app/views/cartes/_form.html.erb
<%= simple_form_for @carte do |f| %>
	<div class="row">
		<div class="form-group col-lg-6">
			<%= f.input :name, label: 'Nom', class: 'form-control' %>
		</div>
		<div class="form-group col-lg-6">
			<%= f.association :type, label: 'Type', class: 'form-control' %>
		</div>
	</div>
	<div class="row">
		<div class="form-group">
			<%= f.association :races, label: 'Races', as: :check_boxes, item_wrapper_tag: :label, item_wrapper_class: 'checkbox-inline' %>
		</div>
	</div>
	<div class="row">
		<div class="form-group col-lg-4">
			<%= f.input :mana, label: 'Mana', class: 'form-control' %>
		</div>
		<div class="form-group col-lg-4">
			<%= f.input :rarete, label: 'Rareté', class: 'form-control' %>
		</div>
	</div>
	<%= f.submit 'Enregistrer', class: 'btn btn-primary'%>
<% end %>

app/views/cartes/_races_list.html.erb
<% if @carte.races.any? %>
	<table class='table'>
		<thread>
			<th>Nom</th>
			<th>Type</th>
			<th>Action</th>
		</thread>
		<tbody>
			<% @carte.races.each do |race| %>
				<tr>
					<td><%= race.name %></td>
					<td><%= type_badge race.type, race.type.color %></td>
					<td><%= link_to 'Afficher', race, class: 'btn btn-info' %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% else %>
	<p>
		Il n'y a pas encore de race.
	</p>
<% end %>

app/views/cartes/edit.html.erb
<h1>Edition d'une Carte</h1>

<%= render 'form' %>

<br>
<p>
	<%= link_to 'Retour', cartes_path, class:'btn btn-default' %>
</p>

app/views/cartes/index.html.erb
<h1>Liste des cartes</h1>

<p>
	<%= link_to 'Ajouter une Carte', new_carte_path, class: 'btn btn-success' %>
</p>

<% if @cartes.any? %>
	<section class="table-responsive">
		<table class="table">
			<thead>
				<tr>
					<th>#</th>
					<th>Nom</th>
					<th>Type</th>
				</tr>
			</thead>
			<tbody>
				<% @cartes.each do |carte| %>
					<tr>			
						<td><%= carte.number %></td>
						<td><%= carte.name %></td>
						<td><%= carte.type ? type_badge(carte.type, carte.type.color) : 'Aucun' %></td>
						<td><%= link_to 'Afficher', carte, class:'btn btn-info' %>
							<%= link_to 'Editer', edit_carte_path(carte), class:'btn btn-warning' %>
							<%= link_to 'Supprimer', carte, 
								method: :delete,
								data: { confirm: "Etes-vous sûr(e) de vouloir supprimer #{carte.name} ?" },
								class: 'btn btn-danger' %>
						</td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</section>
	<%= will_paginate @cartes, renderer: BootstrapPagination::Rails %>
<% else %>
	<p>Il n'y a pas encore de Carte.</p>
<% end %>

app/views/cartes/new.html.erb
<h1>Création d'une Carte</h1>

<%= render 'form' %>
<br>
<%= link_to 'Retour', cartes_path, class:'btn btn-default' %>

app/views/cartes/show.html.erb
<h1>Afficher une Carte</h1>

<p>
	Nom : <%= @carte.name %>
</p>

<p>
	Type:
	<% type = @carte.type %>
	<% if type.nil? -%>
		aucun
	<% else %>
		<%= type_badge type, type.color %>
	<% end %>
</p>
<p>Rareté : <%= @carte.rarete %></p>
<p>Numero : <%= @carte.number %></p>
<p>mana : <%= @carte.mana %></p>

<h2>Liste des Races</h2>

<%= render 'races_list' %>

<p>
	<%= link_to 'Retour', cartes_path, class: 'btn btn-default' %>
</p>

app/views/home/index.html.erb
<h1>
	Bienvenue sur 
	<%= Rails.application.class.parent_name %> !
</h1>
<p>
	<%= link_to 'Liste des Cartes', cartes_path, class: 'btn btn-default' %>
	<%= link_to 'Liste des Types', types_path, class: 'btn btn-default' %>
	<%= link_to 'Liste des Races', races_path, class: 'btn btn-default' %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
 	<meta charset="utf-8">
 	<meta http-equiv="X-UA-Compatible" content="IE=edge">
 	<meta name="viewport" content="width=device-width, initial-scale=1">
 	
	<title>Hearthdex</title>
	
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	<% unless Rails.application.assets.find_asset("#{controller_name}.css").nil? -%>
		<!-- Load controller-specific stylesheet if available -->
		<%= stylesheet_link_tag controller_name, media: 'all', 'data-turbolinks-track' => true %>
	<% end -%>
	
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<% unless Rails.application.assets.find_asset("#{controller_name}.js").nil? -%>
		<!-- Load controller-specific script if available -->
		<%= javascript include_tag controller_name, 'data-turbolinks-track' => true %>
	<% end %>
	
	<%= csrf_meta_tags %>
</head>
<body class=">%= "#{controller_name}-#{action_name}" %>">
	<div class="container">
		<h1>
			<%= link_to Rails.application.class.parent_name, root_path %>
		</h1>
		<% flash.each do |name, msg| -%>
			<div class="alert alert-info alert-<%= name %>">
				<a class="close" data-dismiss="alert">x</a>
				<%= content_tag :div, msg, id: "flash_{name}" %>
			</div>
		<% end -%>
	
		<br>
		<%= yield %>
	</div>
</body>
</html>

app/views/races/_form.html.erb
<%= simple_form_for(@race) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, label: 'Nom' %>
    <%= f.input :description, label: 'Description' %>
    <%= f.association :type, label: 'Type' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Enregistrer', class: 'btn-btn-success' %>
  </div>
<% end %>

app/views/races/edit.html.erb
<h1>Modification d'une race</h1>

<%= render 'form' %>

<%= link_to 'Afficher', @race, class:'btn btn-default' %> |
<%= link_to 'Retour', races_path %>

app/views/races/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Liste des races</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Description</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @races.each do |race| %>
      <tr>
        <td><%= race.name %></td>
        <td><%= race.description %></td>
        <td><%= type_badge(race.type) %></td>
        <td><%= link_to 'Afficher', race, class:'btn btn-info' %></td>
        <td><%= link_to 'Modifier', edit_race_path(race), class:'btn btn-warning' %></td>
        <td><%= link_to 'Supprimer', race, method: :delete, data: { confirm: 'Etes-vous sur(e) ?' }, class:'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Race', new_race_path %>

app/views/races/new.html.erb
<h1>Ajout d'une race</h1>

<%= render 'form' %>

<%= link_to 'Retour', races_path, class:'btn btn-default' %>

app/views/races/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @race.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @race.description %>
</p>

<p>
  <strong>Type:</strong>
  <%= @race.type.name %>
  <%= @race.type.color %>
</p>

<%= link_to 'Modifier', edit_race_path(@race), class:'btn btn-warning' %> |
<%= link_to 'Retour', races_path, class:'btn btn-default' %>

app/views/types/_form.html.erb
<%= form_for(@type) do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td><%= type.name %></td>
        <td><%= type.color %></td>
        <td><%= link_to 'Afficher', type, class:'btn btn-info' %></td>
        <td><%= link_to 'Modifier', edit_type_path(type), class:'btn btn-warning' %></td>
        <td><%= link_to 'Destroy', type, method: :delete, class:'btn btn-danger', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type', new_type_path %>

app/views/types/new.html.erb
<h1>New Type</h1>

<%= render 'form' %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @type.name %>
</p>

<p>
  <strong>Couleur:</strong>
  <%= type_badge(@type, @type.color) %>
</p>

<%= link_to 'Modifier', edit_type_path(@type), class:'btn btn-warning' %> |
<%= link_to 'Retour', types_path, class:'btn btn-default' %>